services:
  dispatcharr:
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.dev
    image: dispatcharr/dispatcharr
    container_name: dispatcharr_dev
    ports:
      - 5656:5656
      - 9191:9191
      - 8001:8001
    volumes:
      - ../:/app
    environment:
      - DISPATCHARR_ENV=dev
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
