services:
  dispatcharr:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: dispatcharr/dispatcharr:alpha-v1
    container_name: dispatcharr
    ports:
      - 9191:9191
    volumes:
      - dispatcharr_db:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0

volumes:
  dispatcharr_db:
